"""What the worklist does not offer, and does not write.

FR-028, FR-031, FR-056.

Three negative properties, each stated as a requirement rather than inherited
silently — because an unstated obligation is the kind a later reader supplies
from habit and then implements against.

**No write path exists.** FR-031 makes an adjusted need-by a session-scoped
what-if, so there is nothing to POST to. Asserted over the route table rather
than over behaviour: a write path that exists and is currently unused is one a
later change makes reachable, and "no handler writes today" is a property of
today's handlers.

**Criticality is never persisted.** FR-028 gives that to E017. This surface
reads it and offers no way to change it.

**There is no authentication and no coordinator identity.** FR-056 records the
inherited scope decision explicitly, and names where a reversal would land:
FR-025's scope and FR-031's adjustment set are the two clauses that would gain
an actor, and neither has one today.
"""

from __future__ import annotations

from typing import Any

import pytest

from api.main import app

#: The methods a read-only surface may answer. `HEAD` and `OPTIONS` are
#: generated by the framework from `GET` and write nothing.
READ_METHODS = frozenset({"GET", "HEAD", "OPTIONS"})


def test_the_route_table_offers_no_write_method() -> None:
    """FR-031. There is nothing here to POST to, and that is structural.

    Asserted over the routes rather than over responses: a write path that
    exists and happens to be unreachable in today's interface is one a later
    change makes reachable without anyone revisiting this requirement.
    """
    for route in app.routes:
        methods = getattr(route, "methods", None)
        if methods is None:
            continue
        offending = set(methods) - READ_METHODS
        assert not offending, f"{getattr(route, 'path', route)} offers {sorted(offending)}"


@pytest.mark.parametrize("method", ["post", "put", "patch", "delete"])
def test_a_write_to_the_worklist_is_refused(
    frozen_run: dict[str, Any], client: Any, method: str
) -> None:
    """The observable form of the same rule."""
    response = getattr(client, method)("/api/v1/worklist")
    assert response.status_code == 405


def test_reading_the_worklist_changes_no_stored_line(
    frozen_run: dict[str, Any], client: Any, connection: Any
) -> None:
    """FR-028, FR-031. Neither criticality nor the need-by date moves.

    Compared as a whole snapshot rather than field by field: a read that wrote
    to some *other* column would pass a check of the two fields this test set
    out to watch, and would be exactly as wrong.
    """
    columns = "po_line_id, need_by_date, criticality, lifecycle_state, is_closed, roster_hash"

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT {columns} FROM purchase_order_line ORDER BY po_line_id")
        before = cursor.fetchall()

    client.get("/api/v1/worklist")
    client.get("/api/v1/worklist", params={"sort": "criticality"})
    line = next(item for item in frozen_run["lines"] if item["case"] == "nominal")
    client.get(
        "/api/v1/worklist", params={"need_by_override": [f"{line['po_line_id']}:2026-12-01"]}
    )

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT {columns} FROM purchase_order_line ORDER BY po_line_id")
        assert cursor.fetchall() == before


def test_reading_the_worklist_writes_no_forecast_artifact(
    frozen_run: dict[str, Any], client: Any, connection: Any
) -> None:
    """The read path reads. A response that wrote to `forecast_run` or
    `line_posterior` would change the artifacts every later figure is computed
    from, which is the one thing Principle I's provenance chain cannot survive."""
    with connection.cursor() as cursor:
        cursor.execute("SELECT count(*), max(artifact_schema_version) FROM forecast_run")
        run_before = cursor.fetchone()
        cursor.execute("SELECT count(*), sum(residual_tail_mass) FROM line_posterior")
        posterior_before = cursor.fetchone()

    client.get("/api/v1/worklist")

    with connection.cursor() as cursor:
        cursor.execute("SELECT count(*), max(artifact_schema_version) FROM forecast_run")
        assert cursor.fetchone() == run_before
        cursor.execute("SELECT count(*), sum(residual_tail_mass) FROM line_posterior")
        assert cursor.fetchone() == posterior_before


def test_the_response_is_the_same_for_every_reader(frozen_run: dict[str, Any], client: Any) -> None:
    """FR-056. No authentication, no coordinator identity, no per-reader
    visibility rule: a response is scoped by the project filter and the
    adjustment set, and by nothing whatever about who is asking.

    Checked by varying the headers an identity would normally travel in. If one
    of them ever changes the body, an actor has appeared in a surface that
    states it has none.
    """
    baseline = client.get("/api/v1/worklist").json()

    for headers in (
        {"Authorization": "Bearer something"},
        {"Cookie": "session=abc123"},
        {"X-User-Id": "coordinator-7"},
        {"X-Forwarded-User": "someone-else"},
    ):
        body = client.get("/api/v1/worklist", headers=headers).json()
        # `generated_at` is the one member two otherwise-identical responses may
        # differ in (FR-020a) — it records when the response was made rather
        # than what it contains.
        body["meta"]["generated_at"] = baseline["meta"]["generated_at"]
        assert body == baseline, f"{sorted(headers)} changed the response"


def test_the_endpoint_declares_no_security_scheme() -> None:
    """FR-056, stated in the contract as well as in behaviour.

    A published schema carrying a security requirement would tell every
    generated client to send a credential this system has no concept of — and
    the first reader to add authentication would find the surface already
    claiming to have it.
    """
    schema = app.openapi()
    assert not schema.get("security")
    assert not schema.get("components", {}).get("securitySchemes")
